import React, { useState } from 'react';
import { Plus, Search, Filter, Zap } from 'lucide-react';

export const WorkoutsTab: React.FC = () => {
  const [searchQuery, setSearchQuery] = useState('');

  return (
    <div className="p-4 pb-20"> {/* Bottom padding for navigation */}
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
          Workouts
        </h1>
        <button className="p-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
          <Plus size={20} />
        </button>
      </div>

      {/* Search and Filter */}
      <div className="flex gap-3 mb-6">
        <div className="flex-1 relative">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={20} />
          <input
            type="text"
            placeholder="Search workouts..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-3 bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-white rounded-lg border-0 focus:ring-2 focus:ring-blue-600"
          />
        </div>
        <button className="p-3 bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors">
          <Filter size={20} />
        </button>
      </div>

      {/* AI Generator Button */}
      <div className="bg-gradient-to-r from-blue-600 to-purple-600 rounded-xl p-6 mb-6 text-white">
        <div className="flex items-center gap-3 mb-3">
          <Zap className="text-yellow-300" size={24} />
          <h3 className="text-lg font-semibold">AI Workout Generator</h3>
        </div>
        <p className="text-blue-100 mb-4">
          Get a personalized workout plan generated by AI based on your goals and preferences.
        </p>
        <button className="bg-white text-blue-600 px-6 py-2 rounded-lg font-medium hover:bg-blue-50 transition-colors">
          Generate Workout
        </button>
      </div>

      {/* Quick Actions */}
      <div className="grid grid-cols-2 gap-4 mb-6">
        <button className="p-4 bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 text-left hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors">
          <h4 className="font-medium text-gray-900 dark:text-white mb-1">Custom Workout</h4>
          <p className="text-sm text-gray-600 dark:text-gray-400">Build your own</p>
        </button>
        <button className="p-4 bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 text-left hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors">
          <h4 className="font-medium text-gray-900 dark:text-white mb-1">Upload PDF</h4>
          <p className="text-sm text-gray-600 dark:text-gray-400">Import routine</p>
        </button>
      </div>

      {/* Workout Templates */}
      <div>
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
          Popular Workouts
        </h3>
        
        {/* Coming Soon Message */}
        <div className="text-center py-12 text-gray-500 dark:text-gray-400">
          <div className="text-4xl mb-4">🚧</div>
          <h4 className="text-lg font-medium mb-2">Coming Soon</h4>
          <p>Workout templates and plans will be available here.</p>
        </div>
      </div>
    </div>
  );
};

export default WorkoutsTab;
